#!/bin/zsh
# five carousel shots for one SKU: $1 slug, $2 name, $3 dose
cd ~/sko-brandbook-site
slug=$1; name=$2; dose=$3; CAT=img/ref2/cat/$slug.png; O=img/products
LABEL="the label exactly as in the first reference image and nothing else: the holographic shield beside the white SKO COMPOUNDS lockup, then $name in large white condensed bold capitals, then $dose in a small hexagonal holographic pill, then 99% Purity and Research Use Only, holographic bands top and bottom, faint molecular linework; every letter fully visible and unchanged; silver crimp cap with a blue flip-off top; clear glass vial"
GLINT="hard low winter sun from the right throwing small star-shaped specular glints off every chrome edge and off the snow crystals, the snow lit deep blue in shadow and pale blue-white on the ridges, the sky a smooth gradient from deep ink blue at the top to bright sky blue at the horizon"
gen() { n=$1; a=$2; p=$3; shift 3; args=(); for r in "$@"; do args+=(--image "$r"); done
  for i in 1 2; do url=$(higgsfield generate create nano_banana_2 "${args[@]}" --aspect_ratio "$a" --wait --prompt "$p" 2>&1 | grep -oE 'https://[^ "]+\.png' | head -1); echo "$slug $n $url"; [ -n "$url" ] && curl -sL "$url" -o "$O/$slug-$n.png" && break; done; }
gen primary 1:1 "Studio product photograph. This exact vial stands upright, centred, on a flat matte ultramarine blue ground (International Klein Blue) that fills the whole frame, seamless, with a soft contact shadow and generous room on every side. Soft large key light from upper left. $LABEL. No text anywhere except the label. Only one vial." $CAT &
gen frost 3:4 "Reproduce the second reference exactly: the same vial pressed into deep powder snow with snow bursting up around it, frost on the cap and shoulders, the same cold blue light, the same deep ultramarine to sky blue backdrop, the same framing; the only change is the vial itself, which is exactly the first reference. $LABEL. No text anywhere except the label. Only one vial." $CAT img/proof/frost.png &
gen pigment 3:4 "Reproduce the second reference exactly: the same bed of ultramarine blue pigment powder, the same raking light, the same vial lying on its side half sunk into the powder with dust on the cap and a clean label, the same framing; the only change is the vial itself, which is exactly the first reference. $LABEL. No text anywhere except the label. Only one vial." $CAT img/proof/powder.png &
gen water 3:4 "Reproduce the second reference exactly: the same vial standing in shallow ultramarine water with hard sun caustics and a broken reflection, the same blue floor, the same framing; the only change is the vial itself, which is exactly the first reference. $LABEL. No text anywhere except the label. Only one vial." $CAT img/proof/water.png &
gen machine 3:4 "Reproduce the second reference exactly: the same large sleek chrome gimbal, rings inside rings on a flowing base, on the same flat matte ultramarine blue ground, the same soft key light, the same framing, the vial held upright at the centre of the inner ring; the only change is the vial itself, which is exactly the first reference. $LABEL. No text anywhere except the label. Only one vial." $CAT img/proof/gimbal.png &
wait; ls -la $O | grep "^-.*$slug"
