#!/bin/zsh
cd ~/sko-brandbook-site
R=img/ref2; O=img/proof
LABEL="the label exactly as in the first reference image: navy label, holographic shield with a helix, the white wordmark SKO above COMPOUNDS, then 99% Purity and Research Use Only, holographic bands top and bottom, faint molecular linework on the label; every letter fully visible and unchanged; silver crimp cap with a blue flip-off top; clear glass vial"
gen() { n=$1; a=$2; p=$3; shift 3
  args=(); for r in "$@"; do args+=(--image "$r"); done
  url=$(higgsfield generate create nano_banana_2 "${args[@]}" --aspect_ratio "$a" --wait --prompt "$p" 2>&1 | grep -oE 'https://[^ "]+\.png' | head -1)
  echo "$n $url"; [ -n "$url" ] && curl -sL "$url" -o "$O/$n.png"; }
gen alpine 3:4 "Product photograph outdoors at altitude, like the second reference. This exact glass vial stands upright encased in a clear block of ice with sharp faceted edges, standing on a frozen lake; snow-covered alpine peaks behind under a deep blue sky, hard mountain sun from the right, the ice refracting the sky. The vial inside the block is crisp and dry-looking. $LABEL, fully readable through the ice. No text anywhere except the label." $R/vial.png $R/iceblock.jpg &
gen frost 3:4 "Product photograph. This exact glass vial stands upright pressed into deep powder snow, snow bursting up around it as if it just landed, the glass and cap frosted at the edges like the second reference, the snow lit cold blue with white sparkle. Deep ultramarine to sky blue backdrop, no horizon. Hard cold light from upper right. $LABEL, clean and fully readable. No text anywhere except the label." $R/vial.png $R/frost1664.jpg &
gen cradle 3:4 "Studio product photograph. A sleek chrome cradle, one continuous flowing form in mirror-polished chrome like the body of the second reference's car, no bolts, no seams, no visible hardware, rises from the ground and curves up to hold this exact glass vial upright in its curve. Flat matte ultramarine blue ground (International Klein Blue) filling the whole frame, seamless. The chrome reflects the blue ground, deep blue in its shadows, white in its highlights. Soft large key light from upper left, long smooth reflections. $LABEL. No text anywhere except the label. No other objects." $R/vial.png $R/chromecar.jpg &
gen badge 3:4 "Studio product photograph. A large chrome shield emblem with a double helix in relief, the exact shape of the shield on the label, mirror-polished with smooth bevelled edges, mounted flat and upright on a flat matte ultramarine blue ground (International Klein Blue) that fills the whole frame; this exact glass vial stands upright in front of the emblem and slightly to the left of its centre, so its reflection in the chrome is not visible behind it. Soft large key light from upper left. $LABEL. No text anywhere except the label, no lettering on the emblem, only one vial in the picture." $R/vial.png $R/chromehearts.jpg &
gen turbine 3:4 "Studio product photograph. A sleek chrome turbine, a smooth polished jet-engine intake with curved blades and a spinner cone, one flowing mirror-chrome form with no bolts or seams, lying on its back so the intake faces up; this exact glass vial stands upright at the centre of the spinner cone. Flat matte ultramarine blue ground (International Klein Blue) filling the whole frame. The chrome reflects the blue ground, deep blue in its shadows, white in its highlights. Soft large key light from upper left. $LABEL. No text anywhere except the label. Only one vial." $R/vial.png $R/chromecar.jpg &
wait; ls -la $O | grep -E "alpine|frost|cradle|badge|turbine"
