#!/bin/zsh
cd ~/sko-brandbook-site
R=img/ref2; O=img/proof
LABEL="the label exactly as in the first reference image: navy label, holographic shield with a helix, the white wordmark SKO above COMPOUNDS, then 99% Purity and Research Use Only, holographic bands top and bottom, faint molecular linework on the label; every letter fully visible and unchanged; silver crimp cap with a blue flip-off top; clear glass vial"
gen() { n=$1; a=$2; p=$3; shift 3
  args=(); for r in "$@"; do args+=(--image "$r"); done
  url=$(higgsfield generate create nano_banana_2 "${args[@]}" --aspect_ratio "$a" --wait --prompt "$p" 2>&1 | grep -oE 'https://[^ "]+\.png' | head -1)
  echo "$n $url"; [ -n "$url" ] && curl -sL "$url" -o "$O/$n.png"; }
gen clamp 3:4 "Studio product photograph. A heavy machined chrome fixture, thick polished steel like the second reference: two massive chrome jaws with hex bolts and milled edges clamp this exact glass vial upright at its shoulder and base, holding it dead centre; the fixture is oversized and weighty, the vial small and precise inside it. Flat matte ultramarine blue ground (International Klein Blue) filling the whole frame, seamless. The chrome reflects the blue ground, deep blue in its shadows, white in its highlights. Hard single key light from upper left. $LABEL. Label fully visible. No text anywhere except the label. No other objects." $R/vial.png $R/engine1.jpg &
gen rotor 3:4 "Studio product photograph. A heavy chrome centrifuge rotor, a thick polished disc with milled slots and a machined hub like the second reference, seen from a low angle; this exact glass vial stands upright in the slot nearest the camera, the other slots empty. Flat matte ultramarine blue ground (International Klein Blue) filling the whole frame, seamless. The chrome reflects the blue ground, deep blue in its shadows, white in its highlights. Hard single key light from upper left. $LABEL. Label fully visible. No text anywhere except the label." $R/vial.png $R/engine2.jpg &
gen emblem 3:4 "Studio product photograph. A heavy cast chrome emblem, a thick polished shield shape with a double helix cut through it in relief, mirror finish with deep bevelled edges like the second reference's cast chrome, standing upright on a flat matte ultramarine blue ground (International Klein Blue) that fills the whole frame; this exact glass vial stands upright in front of the emblem, centred, the emblem twice its height. The chrome reflects the blue ground, deep blue in its shadows, white in its highlights. Hard single key light from upper left. $LABEL. No text anywhere except the label, no lettering on the emblem." $R/vial.png $R/chromehearts.jpg &
gen helixmachine 3:4 "Studio product photograph. A heavy chrome machine part: two thick polished steel helical rails, like a machined double helix, bolted to a chrome base with hex bolts, rising around this exact glass vial which stands upright at the centre of the helix; the rails are thick and weighty, engineered, not decorative. Flat matte ultramarine blue ground (International Klein Blue) filling the whole frame, seamless. The chrome reflects the blue ground, deep blue in its shadows, white in its highlights. Hard single key light from upper left. $LABEL. Label fully visible between the rails. No text anywhere except the label." $R/vial.png $R/engine1.jpg &
wait; ls -la $O | grep -E "clamp|rotor|emblem|helixmachine"
