#!/bin/zsh
cd ~/sko-brandbook-site
R=img/ref2; O=img/proof
LABEL="the label exactly as in the first reference image: navy label, holographic shield with a helix, the white wordmark SKO above COMPOUNDS, then 99% Purity and Research Use Only, holographic bands top and bottom, faint molecular linework on the label; every letter fully visible and unchanged; silver crimp cap with a blue flip-off top; clear glass vial"
gen() { n=$1; a=$2; p=$3; shift 3
  args=(); for r in "$@"; do args+=(--image "$r"); done
  url=$(higgsfield generate create nano_banana_2 "${args[@]}" --aspect_ratio "$a" --wait --prompt "$p" 2>&1 | grep -oE 'https://[^ "]+\.png' | head -1)
  echo "$n $url"; [ -n "$url" ] && curl -sL "$url" -o "$O/$n.png"; }
gen palm 3:4 "Studio product photograph. A hand and forearm made entirely of solid liquid-mirror chrome, a chrome sculpture with no skin anywhere, rises from the bottom edge with the palm open and facing up, fingers relaxed and slightly curled; this exact glass vial stands upright on the open palm, base in contact with the chrome, presented to the camera. Flat matte ultramarine blue ground (International Klein Blue) filling the whole frame, seamless. The chrome reflects the blue ground, deep blue in the shadows, white in the highlights. Hard single key light from upper left. $LABEL. No text anywhere except the label. No other objects." $R/vial.png $R/hand-chrome.jpg &
gen statue 3:4 "Studio photograph. A classical white marble statue fragment, a muscular male torso and one raised forearm, like the second reference, on a flat matte ultramarine blue ground (International Klein Blue) filling the whole frame; this exact glass vial stands upright on the statue's open marble hand, held up toward the camera. Even studio light, crisp shadows, the marble pure white against the absolute blue. $LABEL. No text anywhere except the label. No other objects." $R/vial.png $R/apollo.jpg &
gen cliff 3:4 "Studio photograph. A tall broken block of solid ultramarine blue pigment, rough fractured faces like the second reference, standing on a seamless off-white studio ground; this exact glass vial stands upright on a small flat ledge broken into the side of the block, about two thirds of the way up. The block is matte and absolutely blue, the vial is glass and chrome against it. Soft even light, soft contact shadows. $LABEL. No text anywhere except the label. No other objects." $R/vial.png $R/pigment-cliff.jpg &
gen ice 3:4 "Product photograph. This exact glass vial stands upright frozen a third of the way into a block of clear ice on a flat matte ultramarine blue ground (International Klein Blue); the ice is faceted and cracked inside, refracting the blue, with frost on its top surface; the vial above the ice line is dry and sharp. Cold hard light from the right, deep blue shadow. Everything in the frame is blue except the vial, the ice and the chrome. $LABEL. No text anywhere except the label. No other objects." $R/vial.png $R/snow.jpg &
wait; ls -la $O | grep -E "palm|statue|cliff|ice"
