#!/bin/zsh
cd ~/sko-brandbook-site
R=img/ref2; O=img/proof
LABEL="the label exactly as in the first reference image: navy label, holographic shield with a helix, the white wordmark SKO above COMPOUNDS, then 99% Purity and Research Use Only, holographic bands top and bottom, faint molecular linework on the label; every letter fully visible and unchanged; silver crimp cap with a blue flip-off top; clear glass vial"
gen() { n=$1; a=$2; p=$3; shift 3
  args=(); for r in "$@"; do args+=(--image "$r"); done
  url=$(higgsfield generate create nano_banana_2 "${args[@]}" --aspect_ratio "$a" --wait --prompt "$p" 2>&1 | grep -oE 'https://[^ "]+\.png' | head -1)
  echo "$n $url"; [ -n "$url" ] && curl -sL "$url" -o "$O/$n.png"; }
gen hand2 3:4 "Studio product photograph. A liquid-mirror chrome hand, polished like the second reference, grips this exact glass vial firmly, thumb on one side and four fingers wrapped around the other, holding it upright and presenting it to the camera; the forearm rises from the bottom edge. Flat matte ultramarine blue ground (International Klein Blue) filling the whole frame, seamless. The chrome reflects the blue ground, deep blue in the shadows, white in the highlights. Hard single key light from upper left. $LABEL. Label fully visible between the fingers. No text anywhere except the label. No other objects." $R/vial.png $R/hand-chrome.jpg &
gen water 3:4 "Studio product photograph. This exact glass vial stands upright in shallow ultramarine blue water, submerged to just below the label, on a flat ultramarine blue floor; the water surface is rippled and lit by a hard sun so it throws bright white caustic highlights and deep blue shadows like the second reference; the vial's reflection breaks in the ripples. Everything is blue except the vial. $LABEL. No text anywhere except the label." $R/vial.png $R/water.jpg &
gen snow 3:4 "Product photograph at dusk. This exact glass vial stands upright in a smooth field of fine snow lit entirely by blue light, so the snow reads as soft ultramarine dunes with pale blue highlights on the ridges, like the second reference; the vial is pressed a little way into the snow with snow crystals sparkling around its base. Cold hard light from the right, long blue shadow. No sky, no horizon, the snow fills the frame to the top. $LABEL. No text anywhere except the label." $R/vial.png $R/snow.jpg &
gen ribbon 3:4 "Studio product photograph. This exact glass vial stands upright at the centre on a flat matte ultramarine blue ground (International Klein Blue); a single wide ribbon of liquid-mirror chrome, like the second reference, sweeps once around the vial from behind, passing in front of its lower body below the label and out of frame, reflecting the blue ground in its shadows and white in its highlights. One ribbon only, no other objects. Hard key light from upper left. $LABEL. No text anywhere except the label." $R/vial.png $R/ribbon.jpg &
gen glow 3:4 "Product photograph in a dark room. This exact glass vial stands upright on a black reflective surface; the liquid inside the vial is a luminous ultramarine blue and is the only light source in the frame: it lights the silver cap from below, glows through the glass around the label, throws a pool of blue light onto the surface and fades to black at the edges. No other light, no rim light, no halo behind it. $LABEL, the label lit only by the glow of the liquid, fully readable. No text anywhere except the label." $R/vial.png &
wait; ls -la $O
