#!/bin/zsh
cd ~/sko-brandbook-site
R=img/ref2; O=img/proof
LABEL="the label exactly as in the first reference image: navy label, holographic shield with a helix, the white wordmark SKO above COMPOUNDS, then 99% Purity and Research Use Only, holographic bands top and bottom, faint molecular linework on the label; every letter fully visible and unchanged; silver crimp cap with a blue flip-off top; clear glass vial"
gen() { n=$1; a=$2; p=$3; shift 3
  args=(); for r in "$@"; do args+=(--image "$r"); done
  url=$(higgsfield generate create nano_banana_2 "${args[@]}" --aspect_ratio "$a" --wait --prompt "$p" 2>&1 | grep -oE 'https://[^ "]+\.png' | head -1)
  echo "$n $url"; [ -n "$url" ] && curl -sL "$url" -o "$O/$n.png"; }
MOTOR="a compact cast chrome motor block: a small V-twin engine sculpture in mirror-polished chrome, cylinder heads, cooling fins, a crank pulley and hex bolts, every edge bevelled and the covers engraved with a double-helix relief, finished like heavy silver jewellery rather than a car part"
gen widget 3:4 "Studio product photograph. $MOTOR, about the size of the vial, sits on a flat matte ultramarine blue ground (International Klein Blue) that fills the whole frame; this exact glass vial stands upright beside it, the two objects touching, the vial seated against the motor's side like a cartridge. Both small in the frame with air around them. The chrome reflects the blue ground, deep blue in its shadows, white in its highlights. Hard single key light from upper left, crisp shadows. $LABEL. No text anywhere except the label. No other objects." $R/vial.png $R/pin-engine.jpg &
gen beast 3:4 "Macro product photograph, camera very close and low. $MOTOR fills the frame edge to edge, monumental at this distance, its fins and bolts and helix engraving huge and sharp; this exact glass vial stands upright seated in a machined recess at the front of the block, the label facing the camera. Flat matte ultramarine blue ground (International Klein Blue) behind it. The chrome reflects the blue ground, deep blue in its shadows, white in its highlights. Hard single key light from upper left. $LABEL. No text anywhere except the label. No other objects." $R/vial.png $R/pin-engine.jpg &
gen robohand 3:4 "Product photograph in a dark studio. Two articulated chrome robot hands, mechanical fingers with visible joints, pistons and knuckle plates, mirror-polished dark chrome like the second reference, rise from the bottom of the frame and hold this exact glass vial upright between them, presenting it to the camera. Near-black ground fading to deep ultramarine blue; the chrome reflects ultramarine blue in its shadows and white in its highlights. Hard key light from the upper right, one thin cool rim light. $LABEL, the label fully visible between the fingers. No text anywhere except the label. No other objects." $R/vial.png $R/pin-robohands.jpg &
gen figure 3:4 "Product photograph in a dark studio. A humanoid figure made entirely of mirror-polished chrome, seen from the chest up, head turned slightly, no facial features beyond smooth chrome planes, like the second reference's dark mirror finish; it holds this exact glass vial upright in one chrome hand at shoulder height, presenting it to the camera. Near-black ground fading to deep ultramarine blue; the chrome reflects ultramarine blue in its shadows and white in its highlights. Hard key light from the upper right, one thin cool rim light. $LABEL. No text anywhere except the label. No other objects." $R/vial.png $R/pin-figure.jpg &
wait; ls -la $O | grep -E "widget|beast|robohand|figure"
